# This is a simple CodeBuild build file for PowerShell.
# - pre_build step will ensure the Module Name / Version has not previously been built for production (plans to add this at a later time)
# - build step will perform Clean, ValidateRequirements, Analyze, Test, CreateHelp, Build, Archive
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#runtime-versions-buildspec-file
# https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html

version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - pwsh -command '.\configure_aws_credential.ps1'
      - pwsh -command '.\install_modules.ps1'
  pre_build:
    commands:
      - pwsh -command '$PSVersionTable'
  build:
    commands:
      - pwsh -command 'Invoke-Build -File .\src\<%=$PLASTER_PARAM_ModuleName%>.build.ps1'
artifacts:
  files:
    - '**/*'
  base-directory: 'src\Archive'
reports:
  PesterTestReport:
    files:
      - '**/*'
    file-format: NunitXml
    base-directory: 'src\Artifacts\testOutput'
  CodeCoverageReport:
    files:
      - 'src\Artifacts\ccReport\CodeCoverage.xml'
    file-format: 'JaCoCoXml'