# This is a simple CodeBuild build file for PowerShell.
# - pre_build step will ensure the Module Name / Version has not previously been built for production (plans to add this at a later time)
# - build step will perform Clean, ValidateRequirements, Analyze, Test, CreateHelp, Build, Archive
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#runtime-versions-buildspec-file
# https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html


version: 0.2

phases:
  install:
    commands:
      - powershell -command 'Install-PackageProvider -Name "NuGet" -Confirm:$false -Force -Verbose'
      - powershell -command 'Install-Module -Name PowerShellGet -Repository PSGallery -Force'
      - powershell -command '.\configure_aws_credential.ps1'
      - powershell -command '.\install_modules.ps1'
  pre_build:
    commands:
      # - powershell -command 'New-Item -Path C:\Test -ItemType Directory | Out-Null'
      # - powershell -command 'Invoke-Build -File .\src\<%=$PLASTER_PARAM_ModuleName%>.build.Settings.ps1 -Task ValidateUniqueModuleVersion'
      - powershell -command '$PSVersionTable'
  build:
    commands:
      - powershell -command 'Invoke-Build -File .\src\<%=$PLASTER_PARAM_ModuleName%>.build.ps1'
artifacts:
  files:
    - '**/*'
  base-directory: 'src\Archive'
reports:
  PesterTestReport:
    files:
      - '**/*'
    file-format: NunitXml
    base-directory: 'src\Artifacts\testOutput'
  CodeCoverageReport:
    files:
      - 'src\Artifacts\ccReport\CodeCoverage.xml'
    file-format: 'JaCoCoXml'